SELECT A.CARRERA_ACTAS_ID, CONVERT(B.DESC_SEQ,'UTF8') DESCRIPCION
FROM RC_ACTAS A, RC_ACTAS_SEQ B
WHERE A.PLAN_ESTUDIO_ID = B.ABREV_SEQ
AND B.ABREV_SEQ NOT IN ('L','F','R')
AND A.ESTADO_ACTA = 'APROBADO'
GROUP BY A.CARRERA_ACTAS_ID,B.DESC_SEQ