SELECT DISTINCT A.ACTAS_ID,LPAD(A.REGISTRO_ID, 4, '0') REGISTRO_ID,
    DECODE(C.TIPO_DOCIDENT_ID,
        1,'C.C.',
        2,'T.I.',
        3,'R.C.',
        4,'P.S.',
        5,'C.E.',
        6,'C.A',
        7,'N.I.',
        8,'D.E.'
    ) TIPO_DOCIDENT_ABREV,
    A.DOC_IDENT,
	CONVERT(PADGE_MUNICIPIO.fVAGetDESCRIPCION(C.MUNIC_EXPEDICION), 'UTF8') MUNICIPIO_DOCIDENT,
	CONVERT(C.NOMBRES || ' ' || C.APELLIDOS, 'UTF8') NOMBRE,
	CONVERT(INITCAP(D.TITULO_OTORGADO), 'UTF8') TITULO_DIPLOMA,
	TO_CHAR(A.FECHA_GRADO,'DD') || ' de ' || LOWER(TO_CHAR(A.FECHA_GRADO,'fmMONTH', 'nls_date_language=spanish')) || ' de ' || TO_CHAR(A.FECHA_GRADO, 'YYYY') FECHA_GRADO_FORMATO,
    A.FOLIO_ID,
    A.LIBRO_ID,
	TO_CHAR(A.FECHA_GRADO,'DD') || ' de ' || LOWER(TO_CHAR(A.FECHA_GRADO,'fmMONTH', 'nls_date_language=spanish')) || ' de ' || TO_CHAR(A.FECHA_GRADO, 'YYYY') FECHA_REGISTRO_FORMATO,
    '' CONSECUTIVO_DIPLOMA,
    A.CARRERA_ACTAS_ID,
	CONVERT(D.TITULO_OTORGADO, 'UTF8') TITULO_ACTA,
    A.PROCONSECUTIVO_ID,
    CONVERT(PADPS_PLAN_ESTUDIO.fVAGetDESCRIPCION(A.PLAN_ESTUDIO_ID), 'UTF8') DESC_PLAN,
    A.RESOLUCION_ID,
    A.PLAN_ESTUDIO_ID,
    TO_CHAR(A.FECHA_RESOLUCION,'DD/MM/YYYY HH12:MI:SS AM') FECHA_RESOLUCION,
    A.PERIODO_ID,
    A.ESTUDIANTE_ID,
    A.TIPO_GRADO,
    A.ESTADO_ACTA
FROM RC_ACTAS A,
    RC_ESTUDIANTE B,
    VW_DATBAS_ESTUDIANTE C,
	SN_PROCONSECUTIVO D
WHERE A.ESTADO_ACTA = 'SIN_APROBAR'
AND A.ESTUDIANTE_ID = B.ESTUDIANTE_ID
AND B.ESTUDIANTE_ID = C.ESTUDIANTE_ID
AND A.PROCONSECUTIVO_ID = D.PROCONSECUTIVO_ID