SELECT A.PLAN_ESTUDIO_ID, CONVERT(B.DESCRIPCION, 'UTF8') DESCRIPCION
FROM RC_ACTAS A,PS_PLAN_ESTUDIO B
WHERE A.ESTADO_ACTA = 'APROBADO'
AND A.PLAN_ESTUDIO_ID = B.PLAN_ESTUDIO_ID
GROUP BY A.PLAN_ESTUDIO_ID, B.DESCRIPCION